config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :version_progresses, :only=> [:index, :show] do
  get 'record_progress', :on => :collection
end

app/models/version_progress.rb
class VersionProgress < ActiveRecord::Base
  belongs_to :version

  def self.record_progress(version=nil)
    if version
      VersionProgress.create!(:spent_hours => version.spent_hours, :percentage_done => version.completed_pourcent, :version => version)
    else
      Version.all(:conditions => "status = 'open'").each do |version|
        VersionProgress.create!(:week_no => DateTime.now.strftime('%U'),
                                :spent_hours => version.spent_hours,
                                :percentage_done => version.completed_pourcent,
                                :version => version)
      end
    end
  end

  def self.clean_duplicates
    Version.all(:conditions => "status = 'open'").each do |version|
      (1..52).each do |week_no|
        version_progress = VersionProgress.first(:conditions => ["version_id =? and week_no = ?", version.id, week_no])
        if version_progress
          VersionProgress.destroy_all(["version_id = ? and week_no =? and id <> ? ", version_progress.version_id, version_progress.week_no, version_progress.id])
        end
      end
    end
  end
end

app/controllers/version_progresses_controller.rb
class VersionProgressesController < ApplicationController
  unloadable

  before_filter :require_admin

  include VersionProgressHelper
  helper :version_progress

  def index
    @project = params[:project_id] ? Project.find(params[:project_id]) : Project.first
    redirect_to version_progress_url :action=>:show,:id=>@project.id, :version_id => params[:version_id] if @project
  end

  def show
    @project = Project.find(params[:id])
    @version = @project.versions.exists?(params[:version_id]) ? Version.find(params[:version_id]) : @project.versions.first

    @projects = Project.visible.all(:order => 'name asc')
    @versions = Version.all(:conditions => ["status = 'open' and project_id =?", @project.id], :order => 'name asc')

    from_date = 0
    to_date = DateTime.now

    if params[:period] == 'from_date'
      flash.now[:warning] = "Please enter a date." if params[:from_date].blank?
      from_date = params[:from_date]
    elsif params[:period] == 'between'
      flash.now[:warning] = "Please enter a date range." if params[:from_date].blank? || params[:to_date].blank?
      from_date = params[:from_date]
      to_date = params[:to_date]
    end

    @version_progresses = @version ? VersionProgress.all(:conditions => ["version_id = ? and created_at > ? and created_at < ?", @version.id, from_date, to_date], :order => "created_at desc") : nil

    logger.info "commit is #{params[:commit]}"

    if params[:commit] == "Export to CSV"
      send_data(version_progresses_to_csv(@version_progresses), :type => 'text/csv; header=present', :filename => "export_#{DateTime.now.strftime('%Y-%m-%d_%H-%M')}.csv")
    end

  end

  def record_progress
    VersionProgress.record_progress
    flash.now[:notice] = "Recorded progresses on all active versions."
    redirect_to version_progresses_url
  end

end

app/helpers/version_progress_helper.rb
module VersionProgressHelper
  def display_date(date)
    date.strftime('%Y-%m-%d')
  end

  def display_percentage_done(percentage)
    percentage.to_f.round.to_s
  end

  def display_spent_days(hours)
    (hours/8).round(1).to_s
  end


  def version_progresses_to_csv(progresses, options={})
    decimal_separator = l(:general_csv_decimal_separator)
    encoding = l(:general_csv_encoding)

    export = FCSV.generate(:col_sep => l(:general_csv_separator), :row_sep => "\r\n") do |csv|
      # csv header fields
      csv << ['Date', '% Done', 'Dev Days']
      #csv lines
      progresses.each do |progress|
        csv << [display_date(progress.created_at), display_percentage_done(progress.percentage_done), display_spent_days(progress.spent_hours)]
      end
    end
    export
  end
end

app/views/version_progresses/_shared_header.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag("progress_report.css", :plugin => "redmine_progress_report", :media => "screen") %>
    <%= javascript_include_tag('//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js') %>
    <%= javascript_tag('jQuery.noConflict();') %>
    <%= javascript_include_tag('progress_report.js', :plugin => 'redmine_progress_report') %>
<% end %>


<div class="contextual">
  <%= link_to "Update all progresses", record_progress_version_progresses_url, :class => "icon icon-multiple" %>
</div>


<h2>Progress Report</h2>

app/views/version_progresses/_show_version_progresses.html.erb
<table class="list">
  <thead>
  <tr>
    <th>Date</th>
    <th>% Done</th>
    <th>Spent Dev Days</th>
  </tr>
  </thead>
  <tbody>
  <% @version_progresses.each do |progress| %>
      <tr>
        <td><%= display_date(progress.created_at) %></td>
        <td>
          <%= progress_bar progress.percentage_done, :width => '80px', :legend => "#{display_percentage_done(progress.percentage_done)}%" %>
        </td>
        <td><%= display_spent_days(progress.spent_hours) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/version_progresses/index.html.erb
<%= render :partial => 'shared_header' %>

<%= form_tag version_progresses_url(), :method => :get, :id => "progress_report_form", :class => "new_issue" do %>
    <div class="box tabular">
      <p>
        <label>Project:</label>
        <%= select_tag :project_id, ("<option value=''></option>".html_safe) + project_tree_options_for_select(@projects, :include_blank => true)  %>
      </p>
    </div>
<% end %>

app/views/version_progresses/show.html.erb
<%= render :partial => 'shared_header' %>

<%= form_tag version_progresses_url, :method => :get, :id => "progress_report_form", :class => "new_issue" do %>
    <div class="box tabular">
      <p>
        <label>Project:</label>
        <%= select_tag :project_id, project_tree_options_for_select(@projects, :selected => @project) %>
      </p>

      <%if @version%>
          <p>
            <label>Active Version:</label>
            <%= select_tag :version_id, options_from_collection_for_select(@versions, :id, :name, @version.id)%>
          </p>

          <p>
            <label>Period:</label>
            <%= select_tag :period, options_for_select([ ['All', 'all'], ['From a date till now', 'from_date'], ['Between two dates', 'between']], params[:period]) %>

            <span id="date_range_wrapper" style="display:none">
        <span id="from_date_wrapper">
        <%= text_field_tag :from_date, params[:from_date], :size => 10 %><%= calendar_for('from_date') %>

        </span>

        <span id="to_date_wrapper">
          to
          <%= text_field_tag :to_date, params[:to_date], :size => 10 %><%= calendar_for('to_date') %>
        </span>
        </span>
          </p>

          <label></label>
          <p>
            <%= submit_tag "Preview" %>
            <%= submit_tag "Export to CSV" %>
          </p>
      <%end%>
    </div>
<% end %>

<%= render :partial => "show_version_progresses" if @version_progresses %>